package davidmatos.assignment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author david
 */
public class Business extends javax.swing.JFrame {

    /**
     * Creates new form Business
     */
    public Business() {
        initComponents();
        setSize(1130, 620);
        updateTable();
        addButtons();
        hideButtons();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String facilityName = "";

    ArrayList<JButton> btnBusinessCenterList = new ArrayList<>();
    ArrayList<JButton> btnOfficeBuildingList = new ArrayList<>();
    ArrayList<JButton> btnConferenceRoomList = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtSearchBar = new javax.swing.JTextField();
        btnTargetBuilding = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxFacilityType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnViewFacilities = new javax.swing.JButton();
        btnCommonRoom = new javax.swing.JButton();
        btnMetaPad = new javax.swing.JButton();
        btnMetricCenter = new javax.swing.JButton();
        btnCrusadeBuilding = new javax.swing.JButton();
        btnEstatePlace = new javax.swing.JButton();
        btnMysticRooms = new javax.swing.JButton();
        btnImpactCenter = new javax.swing.JButton();
        btnAspireCenter = new javax.swing.JButton();
        lblMap = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusiness = new javax.swing.JTable();
        txtFacilityName = new javax.swing.JTextField();
        txtFacilityAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1000, 530, 97, 32);

        txtSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBarKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearchBar);
        txtSearchBar.setBounds(800, 230, 260, 30);

        btnTargetBuilding.setText("Target Building");
        btnTargetBuilding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTargetBuildingActionPerformed(evt);
            }
        });
        getContentPane().add(btnTargetBuilding);
        btnTargetBuilding.setBounds(290, 230, 120, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Business Facilities");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 6, 300, 48);

        cbxFacilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business Center", "Office Building", "Conference Room" }));
        getContentPane().add(cbxFacilityType);
        cbxFacilityType.setBounds(805, 91, 160, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Or");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 160, 30, 25);

        btnViewFacilities.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewFacilities.setText("View Facilities");
        btnViewFacilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFacilitiesActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewFacilities);
        btnViewFacilities.setBounds(805, 125, 160, 32);

        btnCommonRoom.setText("Common Room");
        btnCommonRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommonRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnCommonRoom);
        btnCommonRoom.setBounds(360, 190, 120, 23);

        btnMetaPad.setText("Meta Pad");
        btnMetaPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetaPadActionPerformed(evt);
            }
        });
        getContentPane().add(btnMetaPad);
        btnMetaPad.setBounds(250, 330, 130, 23);

        btnMetricCenter.setText("Metric Center");
        btnMetricCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetricCenterActionPerformed(evt);
            }
        });
        getContentPane().add(btnMetricCenter);
        btnMetricCenter.setBounds(350, 400, 120, 23);

        btnCrusadeBuilding.setText("Crusade Building");
        btnCrusadeBuilding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrusadeBuildingActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrusadeBuilding);
        btnCrusadeBuilding.setBounds(100, 460, 150, 23);

        btnEstatePlace.setText("Estate Place");
        btnEstatePlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatePlaceActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstatePlace);
        btnEstatePlace.setBounds(150, 210, 120, 23);

        btnMysticRooms.setText("Mystic Rooms");
        btnMysticRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMysticRoomsActionPerformed(evt);
            }
        });
        getContentPane().add(btnMysticRooms);
        btnMysticRooms.setBounds(470, 320, 120, 23);

        btnImpactCenter.setText("Impact Center");
        btnImpactCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpactCenterActionPerformed(evt);
            }
        });
        getContentPane().add(btnImpactCenter);
        btnImpactCenter.setBounds(80, 330, 120, 23);

        btnAspireCenter.setText("Aspire Center");
        btnAspireCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAspireCenterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAspireCenter);
        btnAspireCenter.setBounds(190, 150, 120, 23);

        lblMap.setIcon(new javax.swing.ImageIcon("C:\\Users\\david\\OneDrive\\Documents\\NetBeansProjects\\assignment\\src\\main\\java\\davidmatos\\assignment\\bristolMap.jpg")); // NOI18N
        getContentPane().add(lblMap);
        lblMap.setBounds(16, 60, 584, 500);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Or search the text box to find the facility");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(700, 200, 481, 25);

        tblBusiness.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "facilityType", "facilityName", "address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBusiness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusinessMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBusiness);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 270, 452, 157);
        getContentPane().add(txtFacilityName);
        txtFacilityName.setBounds(800, 450, 260, 30);
        getContentPane().add(txtFacilityAddress);
        txtFacilityAddress.setBounds(800, 490, 260, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Search Facility");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(670, 230, 120, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Facility Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 490, 123, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Select the facility type that you would like to view");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(684, 60, 389, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Click on the record in the table that you would like to view");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 180, 481, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Facility Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(670, 450, 105, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addButtons() {
        btnBusinessCenterList.addAll(Arrays.asList(btnAspireCenter, btnImpactCenter, btnMetricCenter));
        btnOfficeBuildingList.addAll(Arrays.asList(btnEstatePlace, btnTargetBuilding, btnMetaPad, btnCrusadeBuilding));
        btnConferenceRoomList.addAll(Arrays.asList(btnCommonRoom, btnMysticRooms));
    }

    public void hideButtons() {

        for (int i = 0; i < btnBusinessCenterList.size(); i++) {
            btnBusinessCenterList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnOfficeBuildingList.size(); i++) {
            btnOfficeBuildingList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnConferenceRoomList.size(); i++) {
            btnConferenceRoomList.get(i).setVisible(false);
        }
    }

    public void showButtons() {
        hideButtons();
        switch (cbxFacilityType.getSelectedItem().toString()) {
            case "Business Center" -> {
                for (int i = 0; i < btnBusinessCenterList.size(); i++) {
                    btnBusinessCenterList.get(i).setVisible(true);
                }
            }
            case "Office Building" -> {
                for (int i = 0; i < btnOfficeBuildingList.size(); i++) {
                    btnOfficeBuildingList.get(i).setVisible(true);
                }
            }
            case "Conference Room" -> {
                for (int i = 0; i < btnConferenceRoomList.size(); i++) {
                    btnConferenceRoomList.get(i).setVisible(true);
                }
            }
        }
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home homeScreen = new Home();
        homeScreen.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewFacilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFacilitiesActionPerformed
       showButtons();
    }//GEN-LAST:event_btnViewFacilitiesActionPerformed

    private void btnMetaPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetaPadActionPerformed
        // TODO add your handling code here:
        facilityName = btnMetaPad.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnMetaPadActionPerformed

    private void btnMetricCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetricCenterActionPerformed
        // TODO add your handling code here:
        facilityName = btnMetricCenter.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnMetricCenterActionPerformed

    private void btnCrusadeBuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrusadeBuildingActionPerformed
        // TODO add your handling code here:
        facilityName = btnCrusadeBuilding.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCrusadeBuildingActionPerformed

    private void btnEstatePlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatePlaceActionPerformed
        // TODO add your handling code here:
        facilityName = btnEstatePlace.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnEstatePlaceActionPerformed

    private void btnMysticRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMysticRoomsActionPerformed
        // TODO add your handling code here:
        facilityName = btnMysticRooms.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnMysticRoomsActionPerformed

    private void btnImpactCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpactCenterActionPerformed
        // TODO add your handling code here:
        facilityName = btnImpactCenter.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnImpactCenterActionPerformed

    private void btnAspireCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAspireCenterActionPerformed
        // TODO add your handling code here:
        facilityName = btnAspireCenter.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnAspireCenterActionPerformed

    private void btnCommonRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommonRoomActionPerformed
        // TODO add your handling code here:
        facilityName = btnCommonRoom.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCommonRoomActionPerformed

    private void btnTargetBuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTargetBuildingActionPerformed
        // TODO add your handling code here:
        facilityName = btnTargetBuilding.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnTargetBuildingActionPerformed

    private void tblBusinessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusinessMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblBusiness.getModel();
        int selectedIndex = tblBusiness.getSelectedRow();
        
        String facilityTypeValue;
        int facilityTypeIndex = 0;

        facilityTypeValue = model.getValueAt(selectedIndex, 1).toString();
        txtFacilityName.setText(model.getValueAt(selectedIndex, 2).toString());
        txtFacilityAddress.setText(model.getValueAt(selectedIndex, 3).toString());

        switch (facilityTypeValue) {
            case "Business Center" -> facilityTypeIndex = 0;
            case "Office Building" -> facilityTypeIndex = 1;
            case "Conference Room" -> facilityTypeIndex = 2;
        }
        cbxFacilityType.setSelectedIndex(facilityTypeIndex);
        showButtons();
    }//GEN-LAST:event_tblBusinessMouseClicked

    private void txtSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblBusiness.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblBusiness.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearchBar.getText().trim()));
    }//GEN-LAST:event_txtSearchBarKeyReleased

    public void selectFacilityDetails() {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/david/OneDrive/Documents/CityPlanner.accdb");
            pst = con.prepareStatement("SELECT * FROM Business WHERE facilityName=?");
            pst.setString(1, facilityName);
            rs = pst.executeQuery();

            while (rs.next()) {
                txtFacilityName.setText(rs.getString("facilityName"));
                txtFacilityAddress.setText(rs.getString("address"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void updateTable() {
        try {
            int c;
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/david/OneDrive/Documents/CityPlanner.accdb");
            pst = con.prepareStatement("SELECT * FROM Business");
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel) tblBusiness.getModel();
            dft.setRowCount(0);

            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= c; i++) {
                    vector.add(rs.getString("ID"));
                    vector.add(rs.getString("facilityType"));
                    vector.add(rs.getString("facilityName"));
                    vector.add(rs.getString("address"));
                }
                dft.addRow(vector);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Business().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAspireCenter;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCommonRoom;
    private javax.swing.JButton btnCrusadeBuilding;
    private javax.swing.JButton btnEstatePlace;
    private javax.swing.JButton btnImpactCenter;
    private javax.swing.JButton btnMetaPad;
    private javax.swing.JButton btnMetricCenter;
    private javax.swing.JButton btnMysticRooms;
    private javax.swing.JButton btnTargetBuilding;
    private javax.swing.JButton btnViewFacilities;
    private javax.swing.JComboBox<String> cbxFacilityType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMap;
    private javax.swing.JTable tblBusiness;
    private javax.swing.JTextField txtFacilityAddress;
    private javax.swing.JTextField txtFacilityName;
    private javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
}
