package davidmatos.assignment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author david
 */
public class JobSeeker extends javax.swing.JFrame {

    /**
     * Creates new form JobSeeker
     */
    public JobSeeker() {
        initComponents();
        setSize(1130, 620);
        updateTable();
        addButtons();
        hideButtons();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String facilityName = "";

    ArrayList<JButton> btnJobCenterList = new ArrayList<>();
    ArrayList<JButton> btnFinanceList = new ArrayList<>();
    ArrayList<JButton> btnConstructionList = new ArrayList<>();
    ArrayList<JButton> btnEmergencyServicesList = new ArrayList<>();
    ArrayList<JButton> btnHealthcareList = new ArrayList<>();
    ArrayList<JButton> btnITList = new ArrayList<>();
    ArrayList<JButton> btnLawList = new ArrayList<>();
    ArrayList<JButton> btnSportList = new ArrayList<>();
    ArrayList<JButton> btnMediaList = new ArrayList<>();
    ArrayList<JButton> btnTeachingList = new ArrayList<>();
    ArrayList<JButton> btnComputerScienceList = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCollege = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJobSeeker = new javax.swing.JTable();
        btnMediaClub = new javax.swing.JButton();
        btnComputerKing = new javax.swing.JButton();
        btnFinanceKing = new javax.swing.JButton();
        btnCareerForLife = new javax.swing.JButton();
        btnMediaKey = new javax.swing.JButton();
        btnSportMarvel = new javax.swing.JButton();
        btnConstructionPerfect = new javax.swing.JButton();
        btnCareerClub = new javax.swing.JButton();
        btnEmergencyServices = new javax.swing.JButton();
        btnITGenius = new javax.swing.JButton();
        btnHealthcareNatural = new javax.swing.JButton();
        btnLawPerfect = new javax.swing.JButton();
        btnFinanceClub = new javax.swing.JButton();
        btnConstructionKing = new javax.swing.JButton();
        btnTeachingUnite = new javax.swing.JButton();
        btnConstructionLuxe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxFacilityType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnViewFacilities = new javax.swing.JButton();
        txtFacilityAddress = new javax.swing.JTextField();
        txtFacilityName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblMap = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSearchBar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1000, 530, 97, 32);

        tblJobSeeker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "facilityType", "facilityName", "address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblJobSeeker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJobSeekerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJobSeeker);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 250, 452, 157);

        btnMediaClub.setText("Media Club");
        btnMediaClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaClubActionPerformed(evt);
            }
        });
        getContentPane().add(btnMediaClub);
        btnMediaClub.setBounds(100, 260, 140, 23);

        btnComputerKing.setText("Computer King");
        btnComputerKing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputerKingActionPerformed(evt);
            }
        });
        getContentPane().add(btnComputerKing);
        btnComputerKing.setBounds(350, 350, 120, 23);

        btnFinanceKing.setText("Finance King");
        btnFinanceKing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceKingActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinanceKing);
        btnFinanceKing.setBounds(320, 180, 120, 23);

        btnCareerForLife.setText("Career For Life");
        btnCareerForLife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCareerForLifeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCareerForLife);
        btnCareerForLife.setBounds(410, 190, 130, 23);

        btnMediaKey.setText("Media Key");
        btnMediaKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaKeyActionPerformed(evt);
            }
        });
        getContentPane().add(btnMediaKey);
        btnMediaKey.setBounds(300, 120, 140, 23);

        btnSportMarvel.setText("Sport Marvel");
        btnSportMarvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportMarvelActionPerformed(evt);
            }
        });
        getContentPane().add(btnSportMarvel);
        btnSportMarvel.setBounds(100, 120, 120, 23);

        btnConstructionPerfect.setText("Construction Perfect");
        btnConstructionPerfect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstructionPerfectActionPerformed(evt);
            }
        });
        getContentPane().add(btnConstructionPerfect);
        btnConstructionPerfect.setBounds(150, 210, 150, 23);

        btnCareerClub.setText("Career Club");
        btnCareerClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCareerClubActionPerformed(evt);
            }
        });
        getContentPane().add(btnCareerClub);
        btnCareerClub.setBounds(260, 270, 120, 23);

        btnEmergencyServices.setText("Emergency Services");
        btnEmergencyServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmergencyServicesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmergencyServices);
        btnEmergencyServices.setBounds(210, 340, 140, 23);

        btnITGenius.setText("IT Genius");
        btnITGenius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnITGeniusActionPerformed(evt);
            }
        });
        getContentPane().add(btnITGenius);
        btnITGenius.setBounds(20, 440, 160, 23);

        btnHealthcareNatural.setText("Healthcare Natural");
        btnHealthcareNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealthcareNaturalActionPerformed(evt);
            }
        });
        getContentPane().add(btnHealthcareNatural);
        btnHealthcareNatural.setBounds(250, 470, 150, 23);

        btnLawPerfect.setText("Law Perfect");
        btnLawPerfect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLawPerfectActionPerformed(evt);
            }
        });
        getContentPane().add(btnLawPerfect);
        btnLawPerfect.setBounds(420, 450, 120, 23);

        btnFinanceClub.setText("Finance Club");
        btnFinanceClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceClubActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinanceClub);
        btnFinanceClub.setBounds(380, 410, 120, 23);

        btnConstructionKing.setText("Construction King");
        btnConstructionKing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstructionKingActionPerformed(evt);
            }
        });
        getContentPane().add(btnConstructionKing);
        btnConstructionKing.setBounds(240, 420, 140, 23);

        btnTeachingUnite.setText("Teaching Unite");
        btnTeachingUnite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeachingUniteActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeachingUnite);
        btnTeachingUnite.setBounds(480, 390, 120, 23);

        btnConstructionLuxe.setText("Construction Luxe");
        btnConstructionLuxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstructionLuxeActionPerformed(evt);
            }
        });
        getContentPane().add(btnConstructionLuxe);
        btnConstructionLuxe.setBounds(430, 260, 140, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Job Seeker Facilities");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 6, 350, 48);

        cbxFacilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Job Center", "Finance", "Construction", "Emergency Services", "Healthcare", "IT", "Law", "Sport", "Media", "Teaching", "Computer Science" }));
        getContentPane().add(cbxFacilityType);
        cbxFacilityType.setBounds(810, 80, 160, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Select the facility type that you would like to view");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 50, 389, 25);

        btnViewFacilities.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewFacilities.setText("View Facilities");
        btnViewFacilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFacilitiesActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewFacilities);
        btnViewFacilities.setBounds(810, 110, 160, 32);
        getContentPane().add(txtFacilityAddress);
        txtFacilityAddress.setBounds(800, 470, 260, 30);
        getContentPane().add(txtFacilityName);
        txtFacilityName.setBounds(800, 430, 260, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Facility Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 470, 123, 25);

        lblMap.setIcon(new javax.swing.ImageIcon("C:\\Users\\david\\OneDrive\\Documents\\NetBeansProjects\\assignment\\src\\main\\java\\davidmatos\\assignment\\bristolMap.jpg")); // NOI18N
        getContentPane().add(lblMap);
        lblMap.setBounds(16, 60, 584, 500);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Facility Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(670, 430, 105, 25);

        txtSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBarKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearchBar);
        txtSearchBar.setBounds(810, 210, 260, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Search Facility");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(680, 210, 120, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Or search the text box to find the facility");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(710, 180, 481, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Click on the record in the table that you would like to view");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(640, 160, 481, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Or");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(880, 140, 30, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addButtons() {
        btnJobCenterList.addAll(Arrays.asList(btnCareerClub, btnCareerForLife));
        btnFinanceList.addAll(Arrays.asList(btnFinanceKing, btnFinanceClub));
        btnConstructionList.addAll(Arrays.asList(btnConstructionLuxe, btnConstructionKing, btnConstructionPerfect));
        btnEmergencyServicesList.addAll(Arrays.asList(btnEmergencyServices));
        btnHealthcareList.addAll(Arrays.asList(btnHealthcareNatural));
        btnITList.addAll(Arrays.asList(btnITGenius));
        btnLawList.addAll(Arrays.asList(btnLawPerfect));
        btnSportList.addAll(Arrays.asList(btnSportMarvel));
        btnMediaList.addAll(Arrays.asList(btnMediaKey, btnMediaClub));
        btnTeachingList.addAll(Arrays.asList(btnTeachingUnite));
        btnComputerScienceList.addAll(Arrays.asList(btnComputerKing));
    }

    public void hideButtons() {

        for (int i = 0; i < btnJobCenterList.size(); i++) {
            btnJobCenterList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnFinanceList.size(); i++) {
            btnFinanceList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnConstructionList.size(); i++) {
            btnConstructionList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnEmergencyServicesList.size(); i++) {
            btnEmergencyServicesList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnHealthcareList.size(); i++) {
            btnHealthcareList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnITList.size(); i++) {
            btnITList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnLawList.size(); i++) {
            btnLawList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnSportList.size(); i++) {
            btnSportList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnMediaList.size(); i++) {
            btnMediaList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnTeachingList.size(); i++) {
            btnTeachingList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnComputerScienceList.size(); i++) {
            btnComputerScienceList.get(i).setVisible(false);
        }

    }

    public void showButtons() {
        hideButtons();
        switch (cbxFacilityType.getSelectedItem().toString()) {
            case "Job Center" -> {
                for (int i = 0; i < btnJobCenterList.size(); i++) {
                    btnJobCenterList.get(i).setVisible(true);
                }
            }
            case "Finance" -> {
                for (int i = 0; i < btnFinanceList.size(); i++) {
                    btnFinanceList.get(i).setVisible(true);
                }
            }
            case "Construction" -> {
                for (int i = 0; i < btnConstructionList.size(); i++) {
                    btnConstructionList.get(i).setVisible(true);
                }
            }
            case "Emergency Services" -> {
                for (int i = 0; i < btnEmergencyServicesList.size(); i++) {
                    btnEmergencyServicesList.get(i).setVisible(true);
                }
            }
            case "Healthcare" -> {
                for (int i = 0; i < btnHealthcareList.size(); i++) {
                    btnHealthcareList.get(i).setVisible(true);
                }
            }
            case "IT" -> {
                for (int i = 0; i < btnITList.size(); i++) {
                    btnITList.get(i).setVisible(true);
                }
            }
            case "Law" -> {
                for (int i = 0; i < btnLawList.size(); i++) {
                    btnLawList.get(i).setVisible(true);
                }
            }
            case "Sport" -> {
                for (int i = 0; i < btnSportList.size(); i++) {
                    btnSportList.get(i).setVisible(true);
                }
            }
            case "Media" -> {
                for (int i = 0; i < btnMediaList.size(); i++) {
                    btnMediaList.get(i).setVisible(true);
                }
            }
            case "Teaching" -> {
                for (int i = 0; i < btnTeachingList.size(); i++) {
                    btnTeachingList.get(i).setVisible(true);
                }
            }
            case "Computer Science" -> {
                for (int i = 0; i < btnComputerScienceList.size(); i++) {
                    btnComputerScienceList.get(i).setVisible(true);
                }
            }
        }
    }

    private void tblJobSeekerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJobSeekerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblJobSeeker.getModel();
        int selectedIndex = tblJobSeeker.getSelectedRow();

        String facilityTypeValue;
        int facilityTypeIndex = 0;

        facilityTypeValue = model.getValueAt(selectedIndex, 1).toString();
        txtFacilityName.setText(model.getValueAt(selectedIndex, 2).toString());
        txtFacilityAddress.setText(model.getValueAt(selectedIndex, 3).toString());

        switch (facilityTypeValue) {
            case "Job Center" -> facilityTypeIndex = 0;
            case "Finance" -> facilityTypeIndex = 1;
            case "Construction" -> facilityTypeIndex = 2;
            case "Emergency Services" -> facilityTypeIndex = 3;
            case "Healthcare" -> facilityTypeIndex = 4;
            case "IT" -> facilityTypeIndex = 5;
            case "Law" -> facilityTypeIndex = 6;
            case "Sport" -> facilityTypeIndex = 7;
            case "Media" -> facilityTypeIndex = 8;
            case "Teaching" -> facilityTypeIndex = 9;
            case "Computer Science" -> facilityTypeIndex = 10;
        }
        cbxFacilityType.setSelectedIndex(facilityTypeIndex);
        showButtons();
    }//GEN-LAST:event_tblJobSeekerMouseClicked

    private void btnViewFacilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFacilitiesActionPerformed

        showButtons();

    }//GEN-LAST:event_btnViewFacilitiesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home homeScreen = new Home();
        homeScreen.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMediaClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaClubActionPerformed
        // TODO add your handling code here:
        facilityName = btnMediaClub.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnMediaClubActionPerformed

    private void btnComputerKingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputerKingActionPerformed
        // TODO add your handling code here:
        facilityName = btnComputerKing.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnComputerKingActionPerformed

    private void btnFinanceKingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceKingActionPerformed
        // TODO add your handling code here:
        facilityName = btnFinanceKing.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnFinanceKingActionPerformed

    private void btnCareerForLifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCareerForLifeActionPerformed
        // TODO add your handling code here:
        facilityName = btnCareerForLife.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCareerForLifeActionPerformed

    private void btnMediaKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaKeyActionPerformed
        // TODO add your handling code here:
        facilityName = btnMediaKey.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnMediaKeyActionPerformed

    private void btnSportMarvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportMarvelActionPerformed
        // TODO add your handling code here:
        facilityName = btnSportMarvel.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnSportMarvelActionPerformed

    private void btnConstructionPerfectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstructionPerfectActionPerformed
        // TODO add your handling code here:
        facilityName = btnConstructionPerfect.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnConstructionPerfectActionPerformed

    private void btnCareerClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCareerClubActionPerformed
        // TODO add your handling code here:
        facilityName = btnCareerClub.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCareerClubActionPerformed

    private void btnEmergencyServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmergencyServicesActionPerformed
        // TODO add your handling code here:
        facilityName = btnEmergencyServices.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnEmergencyServicesActionPerformed

    private void btnITGeniusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnITGeniusActionPerformed
        // TODO add your handling code here:
        facilityName = btnITGenius.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnITGeniusActionPerformed

    private void btnHealthcareNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealthcareNaturalActionPerformed
        // TODO add your handling code here:
        facilityName = btnHealthcareNatural.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnHealthcareNaturalActionPerformed

    private void btnLawPerfectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLawPerfectActionPerformed
        // TODO add your handling code here:
        facilityName = btnLawPerfect.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnLawPerfectActionPerformed

    private void btnFinanceClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceClubActionPerformed
        // TODO add your handling code here:
        facilityName = btnFinanceClub.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnFinanceClubActionPerformed

    private void btnConstructionKingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstructionKingActionPerformed
        // TODO add your handling code here:
        facilityName = btnConstructionKing.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnConstructionKingActionPerformed

    private void btnTeachingUniteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeachingUniteActionPerformed
        // TODO add your handling code here:
        facilityName = btnTeachingUnite.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnTeachingUniteActionPerformed

    private void btnConstructionLuxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstructionLuxeActionPerformed
        // TODO add your handling code here:
        facilityName = btnConstructionLuxe.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnConstructionLuxeActionPerformed

    private void txtSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblJobSeeker.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblJobSeeker.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearchBar.getText().trim()));
    }//GEN-LAST:event_txtSearchBarKeyReleased

    public void selectFacilityDetails() {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/david/OneDrive/Documents/CityPlanner.accdb");
            pst = con.prepareStatement("SELECT * FROM JobSeeker WHERE facilityName=?");
            pst.setString(1, facilityName);
            rs = pst.executeQuery();

            while (rs.next()) {
                txtFacilityName.setText(rs.getString("facilityName"));
                txtFacilityAddress.setText(rs.getString("address"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void updateTable() {
        try {
            int c;
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/david/OneDrive/Documents/CityPlanner.accdb");
            pst = con.prepareStatement("SELECT * FROM JobSeeker");
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel) tblJobSeeker.getModel();
            dft.setRowCount(0);

            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= c; i++) {
                    vector.add(rs.getString("ID"));
                    vector.add(rs.getString("facilityType"));
                    vector.add(rs.getString("facilityName"));
                    vector.add(rs.getString("address"));
                }
                dft.addRow(vector);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobSeeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobSeeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobSeeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobSeeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobSeeker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCareerClub;
    private javax.swing.JButton btnCareerForLife;
    private javax.swing.JButton btnComputerKing;
    private javax.swing.JButton btnConstructionKing;
    private javax.swing.JButton btnConstructionLuxe;
    private javax.swing.JButton btnConstructionPerfect;
    private javax.swing.JButton btnEmergencyServices;
    private javax.swing.JButton btnFinanceClub;
    private javax.swing.JButton btnFinanceKing;
    private javax.swing.ButtonGroup btnGroupCollege;
    private javax.swing.JButton btnHealthcareNatural;
    private javax.swing.JButton btnITGenius;
    private javax.swing.JButton btnLawPerfect;
    private javax.swing.JButton btnMediaClub;
    private javax.swing.JButton btnMediaKey;
    private javax.swing.JButton btnSportMarvel;
    private javax.swing.JButton btnTeachingUnite;
    private javax.swing.JButton btnViewFacilities;
    private javax.swing.JComboBox<String> cbxFacilityType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMap;
    private javax.swing.JTable tblJobSeeker;
    private javax.swing.JTextField txtFacilityAddress;
    private javax.swing.JTextField txtFacilityName;
    private javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
}
