package davidmatos.assignment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author david
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        setSize(1130, 620);
        updateTable();
        addButtons();
        hideButtons();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String facilityName = "";

    ArrayList<JButton> btnCollegeList = new ArrayList<>();
    ArrayList<JButton> btnUniList = new ArrayList<>();
    ArrayList<JButton> btnLibraryList = new ArrayList<>();
    ArrayList<JButton> btnGymList = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCollege = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbxFacilityType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnViewFacilities = new javax.swing.JButton();
        btnMeadowsLibrary = new javax.swing.JButton();
        btnCrossroadsLibrary = new javax.swing.JButton();
        btnHawkGym = new javax.swing.JButton();
        btnBlueLibrary = new javax.swing.JButton();
        btnAppleGym = new javax.swing.JButton();
        btnBearGym = new javax.swing.JButton();
        btnSandyCollege = new javax.swing.JButton();
        btnWinterCollege = new javax.swing.JButton();
        btnCentralCollege = new javax.swing.JButton();
        btnSeasideUni = new javax.swing.JButton();
        btnEastUni = new javax.swing.JButton();
        btnPineLibrary = new javax.swing.JButton();
        lblMap = new javax.swing.JLabel();
        txtFacilityAddress = new javax.swing.JTextField();
        txtFacilityName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSearchBar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(null);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1000, 530, 97, 32);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "facilityType", "facilityName", "address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 250, 452, 157);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Student Facilities");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 6, 287, 48);

        cbxFacilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "College", "University", "Library", "Gym" }));
        getContentPane().add(cbxFacilityType);
        cbxFacilityType.setBounds(800, 80, 160, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Select the facility type that you would like to view");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(680, 40, 389, 25);

        btnViewFacilities.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewFacilities.setText("View Facilities");
        btnViewFacilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFacilitiesActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewFacilities);
        btnViewFacilities.setBounds(800, 110, 160, 32);

        btnMeadowsLibrary.setText("Meadows Library");
        btnGroupCollege.add(btnMeadowsLibrary);
        btnMeadowsLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeadowsLibraryActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeadowsLibrary);
        btnMeadowsLibrary.setBounds(250, 220, 130, 23);

        btnCrossroadsLibrary.setText("Crossroads Library");
        btnGroupCollege.add(btnCrossroadsLibrary);
        btnCrossroadsLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrossroadsLibraryActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrossroadsLibrary);
        btnCrossroadsLibrary.setBounds(280, 400, 140, 23);

        btnHawkGym.setText("Hawk Gym");
        btnGroupCollege.add(btnHawkGym);
        btnHawkGym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHawkGymActionPerformed(evt);
            }
        });
        getContentPane().add(btnHawkGym);
        btnHawkGym.setBounds(360, 280, 120, 23);

        btnBlueLibrary.setText("Blue Library");
        btnGroupCollege.add(btnBlueLibrary);
        btnBlueLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlueLibraryActionPerformed(evt);
            }
        });
        getContentPane().add(btnBlueLibrary);
        btnBlueLibrary.setBounds(190, 460, 120, 23);

        btnAppleGym.setText("Apple Gym");
        btnGroupCollege.add(btnAppleGym);
        btnAppleGym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppleGymActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppleGym);
        btnAppleGym.setBounds(470, 500, 120, 23);

        btnBearGym.setText("Bear Gym");
        btnGroupCollege.add(btnBearGym);
        btnBearGym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBearGymActionPerformed(evt);
            }
        });
        getContentPane().add(btnBearGym);
        btnBearGym.setBounds(100, 260, 120, 23);

        btnSandyCollege.setText("Sandy College");
        btnGroupCollege.add(btnSandyCollege);
        btnSandyCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSandyCollegeActionPerformed(evt);
            }
        });
        getContentPane().add(btnSandyCollege);
        btnSandyCollege.setBounds(470, 140, 120, 23);

        btnWinterCollege.setText("Winter College");
        btnGroupCollege.add(btnWinterCollege);
        btnWinterCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWinterCollegeActionPerformed(evt);
            }
        });
        getContentPane().add(btnWinterCollege);
        btnWinterCollege.setBounds(110, 130, 120, 23);

        btnCentralCollege.setText("Central College");
        btnGroupCollege.add(btnCentralCollege);
        btnCentralCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentralCollegeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCentralCollege);
        btnCentralCollege.setBounds(300, 330, 120, 23);

        btnSeasideUni.setText("Seaside University");
        btnSeasideUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeasideUniActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeasideUni);
        btnSeasideUni.setBounds(90, 390, 130, 23);

        btnEastUni.setText("East University");
        btnEastUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEastUniActionPerformed(evt);
            }
        });
        getContentPane().add(btnEastUni);
        btnEastUni.setBounds(480, 340, 120, 23);

        btnPineLibrary.setText("Pine Library");
        btnGroupCollege.add(btnPineLibrary);
        btnPineLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPineLibraryActionPerformed(evt);
            }
        });
        getContentPane().add(btnPineLibrary);
        btnPineLibrary.setBounds(270, 300, 120, 23);

        lblMap.setIcon(new javax.swing.ImageIcon("C:\\Users\\david\\OneDrive\\Documents\\NetBeansProjects\\assignment\\src\\main\\java\\davidmatos\\assignment\\bristolMap.jpg")); // NOI18N
        getContentPane().add(lblMap);
        lblMap.setBounds(16, 60, 584, 500);
        getContentPane().add(txtFacilityAddress);
        txtFacilityAddress.setBounds(800, 470, 260, 30);
        getContentPane().add(txtFacilityName);
        txtFacilityName.setBounds(800, 430, 260, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Facility Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 470, 123, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Facility Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(670, 430, 105, 25);

        txtSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBarKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearchBar);
        txtSearchBar.setBounds(800, 210, 260, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Or");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 140, 30, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Or search the text box to find the facility");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(700, 180, 481, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Search Facility");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(670, 210, 120, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Click on the record in the table that you would like to view");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(630, 160, 481, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addButtons() {
        btnCollegeList.addAll(Arrays.asList(btnCentralCollege, btnWinterCollege, btnSandyCollege));
        btnUniList.addAll(Arrays.asList(btnEastUni, btnSeasideUni));
        btnLibraryList.addAll(Arrays.asList(btnPineLibrary, btnMeadowsLibrary, btnCrossroadsLibrary, btnBlueLibrary));
        btnGymList.addAll(Arrays.asList(btnBearGym, btnAppleGym, btnHawkGym));
    }

    public void hideButtons() {

        for (int i = 0; i < btnCollegeList.size(); i++) {
            btnCollegeList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnUniList.size(); i++) {
            btnUniList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnLibraryList.size(); i++) {
            btnLibraryList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnGymList.size(); i++) {
            btnGymList.get(i).setVisible(false);
        }

    }

    public void showButtons() {
        hideButtons();
        switch (cbxFacilityType.getSelectedItem().toString()) {
            case "College" -> {
                for (int i = 0; i < btnCollegeList.size(); i++) {
                    btnCollegeList.get(i).setVisible(true);
                }
            }
            case "University" -> {
                for (int i = 0; i < btnUniList.size(); i++) {
                    btnUniList.get(i).setVisible(true);
                }
            }
            case "Library" -> {
                for (int i = 0; i < btnLibraryList.size(); i++) {
                    btnLibraryList.get(i).setVisible(true);
                }
            }
            case "Gym" -> {
                for (int i = 0; i < btnGymList.size(); i++) {
                    btnGymList.get(i).setVisible(true);
                }
            }
        }
    }

    private void btnEastUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEastUniActionPerformed
        // TODO add your handling code here:
        facilityName = btnEastUni.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnEastUniActionPerformed

    private void btnSeasideUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeasideUniActionPerformed
        // TODO add your handling code here:
        facilityName = btnSeasideUni.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnSeasideUniActionPerformed

    private void btnCentralCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentralCollegeActionPerformed
        // TODO add your handling code here:
        facilityName = btnCentralCollege.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCentralCollegeActionPerformed

    private void btnWinterCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWinterCollegeActionPerformed
        // TODO add your handling code here:
        facilityName = btnWinterCollege.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnWinterCollegeActionPerformed

    private void btnSandyCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSandyCollegeActionPerformed
        // TODO add your handling code here:
        facilityName = btnSandyCollege.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnSandyCollegeActionPerformed

    private void btnPineLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPineLibraryActionPerformed
        // TODO add your handling code here:
        facilityName = btnPineLibrary.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnPineLibraryActionPerformed

    private void btnMeadowsLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeadowsLibraryActionPerformed
        // TODO add your handling code here:
        facilityName = btnMeadowsLibrary.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnMeadowsLibraryActionPerformed

    private void btnCrossroadsLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrossroadsLibraryActionPerformed
        // TODO add your handling code here:
        facilityName = btnCrossroadsLibrary.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCrossroadsLibraryActionPerformed

    private void btnBearGymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBearGymActionPerformed
        // TODO add your handling code here:
        facilityName = btnBearGym.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnBearGymActionPerformed

    private void btnAppleGymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppleGymActionPerformed
        // TODO add your handling code here:
        facilityName = btnAppleGym.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnAppleGymActionPerformed

    private void btnHawkGymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHawkGymActionPerformed
        // TODO add your handling code here:
        facilityName = btnHawkGym.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnHawkGymActionPerformed

    private void btnBlueLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlueLibraryActionPerformed
        // TODO add your handling code here:
        facilityName = btnBlueLibrary.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnBlueLibraryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home homeScreen = new Home();
        homeScreen.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        int selectedIndex = tblStudents.getSelectedRow();

        String facilityTypeValue;
        int facilityTypeIndex = 0;

        facilityTypeValue = model.getValueAt(selectedIndex, 1).toString();
        txtFacilityName.setText(model.getValueAt(selectedIndex, 2).toString());
        txtFacilityAddress.setText(model.getValueAt(selectedIndex, 3).toString());

        switch (facilityTypeValue) {
            case "College" -> facilityTypeIndex = 0;
            case "University" -> facilityTypeIndex = 1;
            case "Library" -> facilityTypeIndex = 2;
            case "Gym" -> facilityTypeIndex = 3;
        }
        cbxFacilityType.setSelectedIndex(facilityTypeIndex);
        showButtons();
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void btnViewFacilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFacilitiesActionPerformed

        showButtons();
    }//GEN-LAST:event_btnViewFacilitiesActionPerformed

    private void txtSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblStudents.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearchBar.getText().trim()));
    }//GEN-LAST:event_txtSearchBarKeyReleased

    public void selectFacilityDetails() {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/david/OneDrive/Documents/CityPlanner.accdb");
            pst = con.prepareStatement("SELECT * FROM Students WHERE facilityName=?");
            pst.setString(1, facilityName);
            rs = pst.executeQuery();

            while (rs.next()) {
                txtFacilityName.setText(rs.getString("facilityName"));
                txtFacilityAddress.setText(rs.getString("address"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void updateTable() {
        try {
            int c;
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/david/OneDrive/Documents/CityPlanner.accdb");
            pst = con.prepareStatement("SELECT * FROM Students");
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel) tblStudents.getModel();
            dft.setRowCount(0);

            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= c; i++) {
                    vector.add(rs.getString("ID"));
                    vector.add(rs.getString("facilityType"));
                    vector.add(rs.getString("facilityName"));
                    vector.add(rs.getString("address"));
                }
                dft.addRow(vector);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppleGym;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBearGym;
    private javax.swing.JButton btnBlueLibrary;
    private javax.swing.JButton btnCentralCollege;
    private javax.swing.JButton btnCrossroadsLibrary;
    private javax.swing.JButton btnEastUni;
    private javax.swing.ButtonGroup btnGroupCollege;
    private javax.swing.JButton btnHawkGym;
    private javax.swing.JButton btnMeadowsLibrary;
    private javax.swing.JButton btnPineLibrary;
    private javax.swing.JButton btnSandyCollege;
    private javax.swing.JButton btnSeasideUni;
    private javax.swing.JButton btnViewFacilities;
    private javax.swing.JButton btnWinterCollege;
    private javax.swing.JComboBox<String> cbxFacilityType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMap;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtFacilityAddress;
    private javax.swing.JTextField txtFacilityName;
    private javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
}
