package davidmatos.assignment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author david
 */
public class Tourism extends javax.swing.JFrame {

    /**
     * Creates new form Tourism
     */
    public Tourism() {
        initComponents();
        setSize(1130, 620);
        updateTable();
        addButtons();
        hideButtons();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String facilityName = "";

    ArrayList<JButton> btnHotelList = new ArrayList<>();
    ArrayList<JButton> btnRestaurantList = new ArrayList<>();
    ArrayList<JButton> btnAttractionList = new ArrayList<>();
    ArrayList<JButton> btnBankList = new ArrayList<>();
    ArrayList<JButton> btnCinemaList = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtSearchBar = new javax.swing.JTextField();
        btnBerryCinema = new javax.swing.JButton();
        btnAlmondCinema = new javax.swing.JButton();
        btnCoreBank = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxFacilityType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnViewFacilities = new javax.swing.JButton();
        btnCrestBank = new javax.swing.JButton();
        btnComfortHotel = new javax.swing.JButton();
        btnMeritHotel = new javax.swing.JButton();
        btnApplecornInn = new javax.swing.JButton();
        btnWebsterHotel = new javax.swing.JButton();
        btnLuxuryHotel = new javax.swing.JButton();
        btnGrubKitchen = new javax.swing.JButton();
        btnFeastInn = new javax.swing.JButton();
        btnBronzeInn = new javax.swing.JButton();
        btnBirchPark = new javax.swing.JButton();
        btnTropicalThemePark = new javax.swing.JButton();
        btnGiantFerrisWheel = new javax.swing.JButton();
        btnCastleBank = new javax.swing.JButton();
        lblMap = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTourism = new javax.swing.JTable();
        txtFacilityName = new javax.swing.JTextField();
        txtFacilityAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1000, 530, 97, 32);

        txtSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchBarKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearchBar);
        txtSearchBar.setBounds(800, 230, 260, 30);

        btnBerryCinema.setText("Berry Cinema");
        btnBerryCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerryCinemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBerryCinema);
        btnBerryCinema.setBounds(130, 390, 120, 23);

        btnAlmondCinema.setText("Almond Cinema");
        btnAlmondCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmondCinemaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlmondCinema);
        btnAlmondCinema.setBounds(290, 230, 120, 23);

        btnCoreBank.setText("Core Bank");
        btnCoreBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoreBankActionPerformed(evt);
            }
        });
        getContentPane().add(btnCoreBank);
        btnCoreBank.setBounds(430, 470, 120, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Tourism Facilities");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(16, 6, 300, 48);

        cbxFacilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel", "Restaurant", "Attraction", "Bank", "Cinema" }));
        getContentPane().add(cbxFacilityType);
        cbxFacilityType.setBounds(805, 91, 160, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Or");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 160, 30, 25);

        btnViewFacilities.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewFacilities.setText("View Facilities");
        btnViewFacilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFacilitiesActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewFacilities);
        btnViewFacilities.setBounds(805, 125, 160, 32);

        btnCrestBank.setText("Crest Bank");
        btnCrestBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrestBankActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrestBank);
        btnCrestBank.setBounds(360, 190, 120, 23);

        btnComfortHotel.setText("Comfort Hotel");
        btnComfortHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComfortHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnComfortHotel);
        btnComfortHotel.setBounds(250, 370, 130, 23);

        btnMeritHotel.setText("Merit Hotel");
        btnMeritHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeritHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeritHotel);
        btnMeritHotel.setBounds(270, 140, 140, 23);

        btnApplecornInn.setText("Applecorn Inn");
        btnApplecornInn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplecornInnActionPerformed(evt);
            }
        });
        getContentPane().add(btnApplecornInn);
        btnApplecornInn.setBounds(350, 400, 120, 23);

        btnWebsterHotel.setText("Webster Hotel");
        btnWebsterHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebsterHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnWebsterHotel);
        btnWebsterHotel.setBounds(310, 290, 120, 23);

        btnLuxuryHotel.setText("Luxury Hotel");
        btnLuxuryHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuxuryHotelActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuxuryHotel);
        btnLuxuryHotel.setBounds(100, 460, 120, 23);

        btnGrubKitchen.setText("Grub Kitchen");
        btnGrubKitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrubKitchenActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrubKitchen);
        btnGrubKitchen.setBounds(150, 210, 120, 23);

        btnFeastInn.setText("Feast Inn");
        btnFeastInn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeastInnActionPerformed(evt);
            }
        });
        getContentPane().add(btnFeastInn);
        btnFeastInn.setBounds(470, 320, 120, 23);

        btnBronzeInn.setText("Bronze Inn");
        btnBronzeInn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBronzeInnActionPerformed(evt);
            }
        });
        getContentPane().add(btnBronzeInn);
        btnBronzeInn.setBounds(80, 330, 120, 23);

        btnBirchPark.setText("Birch Park");
        btnBirchPark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBirchParkActionPerformed(evt);
            }
        });
        getContentPane().add(btnBirchPark);
        btnBirchPark.setBounds(100, 120, 120, 23);

        btnTropicalThemePark.setText("Tropical Theme Park");
        btnTropicalThemePark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTropicalThemeParkActionPerformed(evt);
            }
        });
        getContentPane().add(btnTropicalThemePark);
        btnTropicalThemePark.setBounds(20, 440, 160, 23);

        btnGiantFerrisWheel.setText("Giant Ferris Wheel");
        btnGiantFerrisWheel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiantFerrisWheelActionPerformed(evt);
            }
        });
        getContentPane().add(btnGiantFerrisWheel);
        btnGiantFerrisWheel.setBounds(430, 230, 140, 23);

        btnCastleBank.setText("Castle Bank");
        btnCastleBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCastleBankActionPerformed(evt);
            }
        });
        getContentPane().add(btnCastleBank);
        btnCastleBank.setBounds(250, 310, 120, 23);

        lblMap.setIcon(new javax.swing.ImageIcon("C:\\Users\\david\\OneDrive\\Documents\\NetBeansProjects\\assignment\\src\\main\\java\\davidmatos\\assignment\\bristolMap.jpg")); // NOI18N
        getContentPane().add(lblMap);
        lblMap.setBounds(16, 60, 584, 500);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Or search the text box to find the facility");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(700, 200, 481, 25);

        tblTourism.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "facilityType", "facilityName", "address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTourism.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTourismMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTourism);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 270, 452, 157);
        getContentPane().add(txtFacilityName);
        txtFacilityName.setBounds(800, 450, 260, 30);
        getContentPane().add(txtFacilityAddress);
        txtFacilityAddress.setBounds(800, 490, 260, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Search Facility");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(670, 230, 120, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Facility Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 490, 123, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Select the facility type that you would like to view");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(684, 60, 389, 25);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Click on the record in the table that you would like to view");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(630, 180, 481, 25);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Facility Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(670, 450, 105, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addButtons() {
        btnHotelList.addAll(Arrays.asList(btnWebsterHotel, btnLuxuryHotel, btnComfortHotel, btnMeritHotel));
        btnRestaurantList.addAll(Arrays.asList(btnApplecornInn, btnGrubKitchen, btnFeastInn, btnBronzeInn));
        btnAttractionList.addAll(Arrays.asList(btnBirchPark, btnTropicalThemePark, btnGiantFerrisWheel));
        btnBankList.addAll(Arrays.asList(btnCastleBank, btnCrestBank, btnCoreBank));
        btnCinemaList.addAll(Arrays.asList(btnAlmondCinema, btnBerryCinema));
    }

    public void hideButtons() {

        for (int i = 0; i < btnHotelList.size(); i++) {
            btnHotelList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnRestaurantList.size(); i++) {
            btnRestaurantList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnAttractionList.size(); i++) {
            btnAttractionList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnBankList.size(); i++) {
            btnBankList.get(i).setVisible(false);
        }
        for (int i = 0; i < btnCinemaList.size(); i++) {
            btnCinemaList.get(i).setVisible(false);
        }

    }

    public void showButtons() {
        hideButtons();
        switch (cbxFacilityType.getSelectedItem().toString()) {
            case "Hotel" -> {
                for (int i = 0; i < btnHotelList.size(); i++) {
                    btnHotelList.get(i).setVisible(true);
                }
            }
            case "Restaurant" -> {
                for (int i = 0; i < btnRestaurantList.size(); i++) {
                    btnRestaurantList.get(i).setVisible(true);
                }
            }
            case "Attraction" -> {
                for (int i = 0; i < btnAttractionList.size(); i++) {
                    btnAttractionList.get(i).setVisible(true);
                }
            }
            case "Bank" -> {
                for (int i = 0; i < btnBankList.size(); i++) {
                    btnBankList.get(i).setVisible(true);
                }
            }
            case "Cinema" -> {
                for (int i = 0; i < btnCinemaList.size(); i++) {
                    btnCinemaList.get(i).setVisible(true);
                }
            }
        }
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Home homeScreen = new Home();
        homeScreen.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewFacilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFacilitiesActionPerformed
       showButtons();
    }//GEN-LAST:event_btnViewFacilitiesActionPerformed

    private void btnComfortHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComfortHotelActionPerformed
        // TODO add your handling code here:
        facilityName = btnComfortHotel.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnComfortHotelActionPerformed

    private void btnMeritHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeritHotelActionPerformed
        // TODO add your handling code here:
        facilityName = btnMeritHotel.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnMeritHotelActionPerformed

    private void btnApplecornInnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplecornInnActionPerformed
        // TODO add your handling code here:
        facilityName = btnApplecornInn.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnApplecornInnActionPerformed

    private void btnWebsterHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebsterHotelActionPerformed
        // TODO add your handling code here:
        facilityName = btnWebsterHotel.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnWebsterHotelActionPerformed

    private void btnLuxuryHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuxuryHotelActionPerformed
        // TODO add your handling code here:
        facilityName = btnLuxuryHotel.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnLuxuryHotelActionPerformed

    private void btnGrubKitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrubKitchenActionPerformed
        // TODO add your handling code here:
        facilityName = btnGrubKitchen.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnGrubKitchenActionPerformed

    private void btnFeastInnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeastInnActionPerformed
        // TODO add your handling code here:
        facilityName = btnFeastInn.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnFeastInnActionPerformed

    private void btnBronzeInnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBronzeInnActionPerformed
        // TODO add your handling code here:
        facilityName = btnBronzeInn.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnBronzeInnActionPerformed

    private void btnBirchParkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBirchParkActionPerformed
        // TODO add your handling code here:
        facilityName = btnBirchPark.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnBirchParkActionPerformed

    private void btnTropicalThemeParkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTropicalThemeParkActionPerformed
        // TODO add your handling code here:
        facilityName = btnTropicalThemePark.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnTropicalThemeParkActionPerformed

    private void btnGiantFerrisWheelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiantFerrisWheelActionPerformed
        // TODO add your handling code here:
        facilityName = btnGiantFerrisWheel.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnGiantFerrisWheelActionPerformed

    private void btnCastleBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCastleBankActionPerformed
        // TODO add your handling code here:
        facilityName = btnCastleBank.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCastleBankActionPerformed

    private void btnCrestBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrestBankActionPerformed
        // TODO add your handling code here:
        facilityName = btnCrestBank.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCrestBankActionPerformed

    private void btnCoreBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoreBankActionPerformed
        // TODO add your handling code here:
        facilityName = btnCoreBank.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnCoreBankActionPerformed

    private void btnAlmondCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmondCinemaActionPerformed
        // TODO add your handling code here:
        facilityName = btnAlmondCinema.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnAlmondCinemaActionPerformed

    private void btnBerryCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerryCinemaActionPerformed
        // TODO add your handling code here:
        facilityName = btnBerryCinema.getText();
        selectFacilityDetails();
    }//GEN-LAST:event_btnBerryCinemaActionPerformed

    private void tblTourismMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTourismMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblTourism.getModel();
        int selectedIndex = tblTourism.getSelectedRow();
        
        String facilityTypeValue;
        int facilityTypeIndex = 0;

        facilityTypeValue = model.getValueAt(selectedIndex, 1).toString();
        txtFacilityName.setText(model.getValueAt(selectedIndex, 2).toString());
        txtFacilityAddress.setText(model.getValueAt(selectedIndex, 3).toString());

        switch (facilityTypeValue) {
            case "Hotel" -> facilityTypeIndex = 0;
            case "Restaurant" -> facilityTypeIndex = 1;
            case "Attraction" -> facilityTypeIndex = 2;
            case "Bank" -> facilityTypeIndex = 3;
            case "Cinema" -> facilityTypeIndex = 4;
        }
        cbxFacilityType.setSelectedIndex(facilityTypeIndex);
        showButtons();
    }//GEN-LAST:event_tblTourismMouseClicked

    private void txtSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchBarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblTourism.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblTourism.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearchBar.getText().trim()));
    }//GEN-LAST:event_txtSearchBarKeyReleased

    public void selectFacilityDetails() {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/david/OneDrive/Documents/CityPlanner.accdb");
            pst = con.prepareStatement("SELECT * FROM Tourism WHERE facilityName=?");
            pst.setString(1, facilityName);
            rs = pst.executeQuery();

            while (rs.next()) {
                txtFacilityName.setText(rs.getString("facilityName"));
                txtFacilityAddress.setText(rs.getString("address"));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void updateTable() {
        try {
            int c;
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://C:/Users/david/OneDrive/Documents/CityPlanner.accdb");
            pst = con.prepareStatement("SELECT * FROM Tourism");
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel) tblTourism.getModel();
            dft.setRowCount(0);

            while (rs.next()) {
                Vector vector = new Vector();
                for (int i = 1; i <= c; i++) {
                    vector.add(rs.getString("ID"));
                    vector.add(rs.getString("facilityType"));
                    vector.add(rs.getString("facilityName"));
                    vector.add(rs.getString("address"));
                }
                dft.addRow(vector);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tourism.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tourism.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tourism.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tourism.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tourism().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmondCinema;
    private javax.swing.JButton btnApplecornInn;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBerryCinema;
    private javax.swing.JButton btnBirchPark;
    private javax.swing.JButton btnBronzeInn;
    private javax.swing.JButton btnCastleBank;
    private javax.swing.JButton btnComfortHotel;
    private javax.swing.JButton btnCoreBank;
    private javax.swing.JButton btnCrestBank;
    private javax.swing.JButton btnFeastInn;
    private javax.swing.JButton btnGiantFerrisWheel;
    private javax.swing.JButton btnGrubKitchen;
    private javax.swing.JButton btnLuxuryHotel;
    private javax.swing.JButton btnMeritHotel;
    private javax.swing.JButton btnTropicalThemePark;
    private javax.swing.JButton btnViewFacilities;
    private javax.swing.JButton btnWebsterHotel;
    private javax.swing.JComboBox<String> cbxFacilityType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMap;
    private javax.swing.JTable tblTourism;
    private javax.swing.JTextField txtFacilityAddress;
    private javax.swing.JTextField txtFacilityName;
    private javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
}
